FROM mariadb:latest

COPY init.sql /docker-entrypoint-initdb.d/sql/
COPY procedures.sql /docker-entrypoint-initdb.d/sql/
COPY default_files.sql /docker-entrypoint-initdb.d/sql/
COPY init.sh /docker-entrypoint-initdb.d/
